DROP TABLE IF EXISTS CODE_CATALOGUE;

CREATE TABLE CODE_CATALOGUE (
  code              BIGINT PRIMARY KEY,
  ean13             BIGINT      NOT NULL,
  quantite_multiple INT      NOT NULL,
  date_creation     DATETIME NOT NULL
)
  DEFAULT CHARACTER SET UTF8
  COLLATE UTF8_unicode_ci
  ENGINE = InnoDB;

LOAD DATA LOCAL INFILE '/home/kaso/exports/KASO_CODECATALOGUE.CSV'
INTO TABLE CODE_CATALOGUE
CHARACTER SET 'latin2'
FIELDS TERMINATED BY ';'
IGNORE 1 LINES
(code, ean13, quantite_multiple, @date_creation, @dummy)
SET date_creation = STR_TO_DATE(@date_creation,'%e/%c/%Y');

DELETE FROM CODE_CATALOGUE WHERE code NOT IN (SELECT code FROM ARTICLE);

ALTER TABLE kaso.CODE_CATALOGUE ADD CONSTRAINT CODE_CATALOGUE_ARTICLE_FK FOREIGN KEY (code) REFERENCES kaso.ARTICLE(code);
