 
SET FOREIGN_KEY_CHECKS=0;
 
DROP TABLE IF EXISTS EMPLACEMENT;

CREATE TABLE EMPLACEMENT (
  code                   INT PRIMARY KEY,
  libelle                VARCHAR(255) NOT NULL
)
  DEFAULT CHARACTER SET UTF8
  COLLATE UTF8_unicode_ci
  ENGINE = InnoDB;


LOAD DATA LOCAL INFILE '/home/kaso/exports/KASO_Emplacement.CSV'
INTO TABLE EMPLACEMENT
CHARACTER SET 'latin2'
FIELDS TERMINATED BY ';'
IGNORE 1 LINES
(code, libelle);

SET FOREIGN_KEY_CHECKS=1;
