DROP TABLE IF EXISTS MODESDEPAIEMENT;

CREATE TABLE IF NOT EXISTS MODESDEPAIEMENT (
  id tinyint(3) unsigned NOT NULL,
  nom varchar(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `MODESDEPAIEMENT`
 ADD PRIMARY KEY (`id`);
