SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS PROVENANCE;

CREATE TABLE PROVENANCE (
  code                   INT PRIMARY KEY,
  libelle                VARCHAR(255) NOT NULL
)
  DEFAULT CHARACTER SET UTF8
  COLLATE UTF8_unicode_ci
  ENGINE = InnoDB;


LOAD DATA LOCAL INFILE '/home/kaso/exports/KASO_Provenance.CSV'
INTO TABLE PROVENANCE
CHARACTER SET 'latin2'
FIELDS TERMINATED BY ';'
IGNORE 1 LINES
(code, libelle); 
 
SET FOREIGN_KEY_CHECKS=1;
