SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS RAYON;

CREATE TABLE RAYON (
  code                   VARCHAR(56) PRIMARY KEY,
  libelle                VARCHAR(255) NOT NULL
)
  DEFAULT CHARACTER SET UTF8
  COLLATE UTF8_unicode_ci
  ENGINE = InnoDB;


LOAD DATA LOCAL INFILE '/home/kaso/exports/KASO_Rayon.CSV'
INTO TABLE RAYON
CHARACTER SET 'latin2'
FIELDS TERMINATED BY ';'
IGNORE 1 LINES
(code, libelle); 
 
SET FOREIGN_KEY_CHECKS=1;
