
CREATE TABLE IF NOT EXISTS STATJOUR (
  date       DATE PRIMARY KEY,
  ca_ht      DECIMAL(10, 6) NOT NULL,
  ca_ttc     DECIMAL(10, 6) NOT NULL,
  nb_clients INT            NOT NULL
)
  DEFAULT CHARACTER SET UTF8
  COLLATE UTF8_unicode_ci
  ENGINE = InnoDB;
