DROP TABLE IF EXISTS TMP_STATREGLT;

CREATE TABLE IF NOT EXISTS TMP_STATREGLT (
  date date NOT NULL,
  reglement_id int(11) NOT NULL,
  reglement varchar(32) NOT NULL,
  montant float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

